
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt_app
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nuxt_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
